# 查询每日交易的返回状态
DAILY_SETTLEMENT_RESULT_CODE_OK = 1001  # 返回结果正常
DAILY_SETTLEMENT_RESULT_CODE_UNKNOW = 1002  # 未知异常
DAILY_SETTLEMENT_RESULT_CODE_NOT_TRADE = 1003  # 非交易日
DAILY_SETTLEMENT_RESULT_CODE_NOT_REGISTER = 1004  # 尚未注册